version: "3.8"

services:
#  web:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    image: "friends:latest"
#    environment:
#      DB_URL: "db"
#      REDIS_URL: "redis"
#    depends_on:
#      - redis
#      - db
#    ports:
#    - 8000:80

  redis:
    image: "redis:alpine"
    ports:
    - 6379:6379
  db:
    image: "postgres:13-alpine"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: test
      POSTGRES_DB: users
    ports:
    - 5432:5432


